#test:
#  tags:
#  - maven
#  script:
#  - mvn clean test -Pspark3 -Pflink-bundle-shade-hive2

deploy:
  stage: deploy
  tags:
  - maven
  only:
  - release-0.10.0-qihoo.4@big-data/hudi
  script:
  - mvn clean deploy -DskipTests -Pspark3 -Pflink-bundle-shade-hive2
